-- SQL실습 공통 검증 테이블 스키마 (참고용 문서)
--
-- 이 파일은 그대로 실행하는 대상이 아니라, JOIN-표준JOIN/NULL 두 실습 폴더의
-- Oracle/01_prepare.sql · SQLServer/01_prepare.sql이 각자의 방언으로 만드는
-- 세 테이블의 "논리 스키마"를 한곳에 문서화한 것이다. 실제 CREATE TABLE 문은
-- 각 DBMS 폴더의 01_prepare.sql에 자료형을 맞춰 다시 작성돼 있다.
--
-- 세 테이블의 역할:
--   sql_example_expectation : 예제별 기대값(정답표). 01_prepare.sql이 채운다.
--   sql_example_result      : 예제별 실제 실행 결과 1행. 02_examples.sql이 채운다.
--   sql_example_validation  : PASS/FAIL 판정 결과. 02_validate.py(Python)가 채운다.

-- =====================================================================
-- sql_example_expectation — 정답표
-- =====================================================================
-- example_id              예제 식별자, 예: 'J09', 'N15' (토픽 접두어 J=JOIN, N=NULL)
-- topic                   'JOIN' 또는 'NULL'
-- concept                 대상 마크다운의 개념명(한글)
-- expected_row_count      이 예제가 sql_example_result에 남겨야 할 행 수(대개 1)
--                         또는 원본 조인/조회의 예상 행 수(J21처럼 그대로 COUNT(*)인 경우)
-- expected_numeric_value  숫자로 검증할 핵심 값(COUNT/SUM/AVG 등)
-- expected_text_value     문자열로 검증할 핵심 값(필요한 예제만)
-- dbms_name               'ORACLE' 또는 'SQLSERVER' — 같은 example_id라도
--                         DBMS별 기대값이 다를 수 있다(예: N32 정렬 위치,
--                         N35 UNIQUE의 NULL 허용 개수)
-- note                    예상 결과를 구체적으로 설명하는 한 줄(예: "id2는 1x2=2행")
--
-- Oracle 예시 자료형: example_id VARCHAR2(10), topic VARCHAR2(10), ...
-- SQL Server 예시 자료형: example_id VARCHAR(10), topic VARCHAR(10), ...

-- =====================================================================
-- sql_example_result — 실제 실행 결과 (예제당 정확히 1행)
-- =====================================================================
-- example_id              sql_example_expectation.example_id와 동일 키
-- actual_row_count        이 예제의 INSERT SELECT가 sql_example_result에
--                          "물리적으로 남기는 행 수". 기본적으로 항상 1이다
--                          (아래 규칙 참고). J21/N29처럼 예외적으로 원본
--                          COUNT(*) 자체를 검증 대상으로 삼는 옛 예제가 남아
--                          있을 수 있으나, JOIN-NULL-통합 폴더는 이 예외를
--                          쓰지 않는다.
-- actual_numeric_value    COUNT/SUM/AVG/그룹수 등 이 예제가 실제로 검증하려는
--                          핵심 수치. "행이 몇 개 나오는가"를 확인하는 예제라도
--                          그 COUNT(*) 값은 여기(actual_numeric_value)에 담지
--                          actual_row_count에 담지 않는다.
-- actual_text_value       검증하려는 문자열 결과 또는 상태(예: 'RAW_NULL'/'RAW_ZERO')
-- executed_at             02_examples.sql 실행 시각(재실행 시 갱신됨)
--
-- 설계 원칙: 02_examples.sql은 매 예제를 "SELECT 'ID', 집계식... " 형태로
-- 감싸 항상 정확히 1행을 INSERT한다. 이렇게 하면 02_validate.py가 항상
-- "example_id 하나 = 결과 한 행"만 비교하면 되어 로직이 단순해진다.
--
-- actual_row_count / actual_numeric_value 사용 규칙 (JOIN-NULL-통합 폴더는
-- 예외 없이 이 규칙을 따른다 - README "검증 스키마" 절 참고):
--   INSERT INTO sql_example_result
--   SELECT 'JNxx', 1, COUNT(*), NULL, 현재시각
--   FROM ...;
-- 위처럼 actual_row_count 자리에는 항상 리터럴 1을 쓰고, 검증하려는 COUNT는
-- actual_numeric_value 자리에 쓴다. 다음처럼 COUNT 결과를 actual_row_count에
-- 직접 넣는 방식은 쓰지 않는다:
--   SELECT 'JNxx', COUNT(*), NULL, NULL, 현재시각   -- 이렇게 쓰지 않는다
-- 하나의 예제에서 두 개의 수치(예: COUNT(*)와 COUNT(우측열))를 동시에 검증해야
-- 하면 example_id를 JNxxA/JNxxB로 나눠 각각 하나의 수치만 담는다.
--
-- sql_example_validation.status는 PASS/FAIL/NO_RESULT 세 가지로만 판정한다.
-- NO_RESULT는 sql_example_expectation에는 있지만 sql_example_result에 해당
-- example_id 행이 없는 경우(02_examples.sql 미실행, 또는 실제 DB 연결 없이
-- 정적 점검만 수행한 경우)이며, 집계 시 PASS/FAIL 어느 쪽에도 넣지 않고
-- pass_count/fail_count/no_result_count/total_count로 항상 구분해서 센다.

-- =====================================================================
-- sql_example_validation — PASS/FAIL 판정
-- =====================================================================
-- example_id              키
-- status                  'PASS' / 'FAIL' / 'NO_RESULT'
-- expected_value          02_validate.py가 만든 사람이 읽을 수 있는 기대값 요약
-- actual_value            사람이 읽을 수 있는 실제값 요약
-- validation_message      불일치 시 구체적 사유, 일치 시 "expected와 actual 일치"

-- =====================================================================
-- 재현성 원칙
-- =====================================================================
-- - 01_prepare.sql은 항상 기존 세 테이블(및 예제용 테이블)을 DROP 후 재생성한다.
-- - 02_examples.sql은 sql_example_result를 예제 실행 직전 example_id별로 지우고
--   다시 INSERT하므로 여러 번 실행해도 중복 행이 쌓이지 않는다.
-- - example_id는 마크다운 개념 순서를 그대로 반영한 고정 문자열이며 실행마다
--   바뀌지 않는다.
