-- SQL실습 공통 검증 테이블 스키마 (참고용 문서)
--
-- 이 파일은 그대로 실행하는 대상이 아니라, JOIN-표준JOIN/NULL 두 실습 폴더의
-- Oracle/01_prepare.sql · SQLServer/01_prepare.sql이 각자의 방언으로 만드는
-- 세 테이블의 "논리 스키마"를 한곳에 문서화한 것이다. 실제 CREATE TABLE 문은
-- 각 DBMS 폴더의 01_prepare.sql에 자료형을 맞춰 다시 작성돼 있다.
--
-- 세 테이블의 역할:
--   sql_example_expectation : 예제별 기대값(정답표). 01_prepare.sql이 채운다.
--   sql_example_result      : 예제별 실제 실행 결과 1행. 02_examples.sql이 채운다.
--   sql_example_validation  : PASS/FAIL 판정 결과. 02_validate.py(Python)가 채운다.

-- =====================================================================
-- sql_example_expectation — 정답표
-- =====================================================================
-- example_id              예제 식별자, 예: 'J09', 'N15' (토픽 접두어 J=JOIN, N=NULL)
-- topic                   'JOIN' 또는 'NULL'
-- concept                 대상 마크다운의 개념명(한글)
-- expected_row_count      이 예제가 sql_example_result에 남겨야 할 행 수(대개 1)
--                         또는 원본 조인/조회의 예상 행 수(J21처럼 그대로 COUNT(*)인 경우)
-- expected_numeric_value  숫자로 검증할 핵심 값(COUNT/SUM/AVG 등)
-- expected_text_value     문자열로 검증할 핵심 값(필요한 예제만)
-- dbms_name               'ORACLE' 또는 'SQLSERVER' — 같은 example_id라도
--                         DBMS별 기대값이 다를 수 있다(예: N32 정렬 위치,
--                         N35 UNIQUE의 NULL 허용 개수)
-- note                    예상 결과를 구체적으로 설명하는 한 줄(예: "id2는 1x2=2행")
--
-- Oracle 예시 자료형: example_id VARCHAR2(10), topic VARCHAR2(10), ...
-- SQL Server 예시 자료형: example_id VARCHAR(10), topic VARCHAR(10), ...

-- =====================================================================
-- sql_example_result — 실제 실행 결과 (예제당 정확히 1행)
-- =====================================================================
-- example_id              sql_example_expectation.example_id와 동일 키
-- actual_row_count        해당 예제 쿼리를 감싼 COUNT(*) 결과(또는 원본 행수)
-- actual_numeric_value    숫자 검증 대상 실제값
-- actual_text_value       문자열 검증 대상 실제값
-- executed_at             02_examples.sql 실행 시각(재실행 시 갱신됨)
--
-- 설계 원칙: 02_examples.sql은 매 예제를 "SELECT 'ID', 집계식... " 형태로
-- 감싸 항상 정확히 1행을 INSERT한다. 이렇게 하면 02_validate.py가 항상
-- "example_id 하나 = 결과 한 행"만 비교하면 되어 로직이 단순해진다.

-- =====================================================================
-- sql_example_validation — PASS/FAIL 판정
-- =====================================================================
-- example_id              키
-- status                  'PASS' / 'FAIL' / 'SKIPPED(...)'
-- expected_value          02_validate.py가 만든 사람이 읽을 수 있는 기대값 요약
-- actual_value            사람이 읽을 수 있는 실제값 요약
-- validation_message      불일치 시 구체적 사유, 일치 시 "expected와 actual 일치"

-- =====================================================================
-- 재현성 원칙
-- =====================================================================
-- - 01_prepare.sql은 항상 기존 세 테이블(및 예제용 테이블)을 DROP 후 재생성한다.
-- - 02_examples.sql은 sql_example_result를 예제 실행 직전 example_id별로 지우고
--   다시 INSERT하므로 여러 번 실행해도 중복 행이 쌓이지 않는다.
-- - example_id는 마크다운 개념 순서를 그대로 반영한 고정 문자열이며 실행마다
--   바뀌지 않는다.
